# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Termipost < Formula
  desc "A Postman-like HTTP client for the terminal."
  homepage "https://github.com/gabriel-ballesteros/termipost"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gabriel-ballesteros/termipost/releases/download/v1.0.2/termipost_1.0.2_darwin_amd64.tar.gz"
      sha256 "0da7ec8e4ada710618d16b220f2b82e461f71bfe5fe904ac0c686f6c01ef0bab"

      define_method(:install) do
        bin.install "termipost"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gabriel-ballesteros/termipost/releases/download/v1.0.2/termipost_1.0.2_darwin_arm64.tar.gz"
      sha256 "12426f3c01f58cc77856f5c6ed35117c53e93aea35b51e7b9e6a88ff9d184a7e"

      define_method(:install) do
        bin.install "termipost"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gabriel-ballesteros/termipost/releases/download/v1.0.2/termipost_1.0.2_linux_amd64.tar.gz"
      sha256 "7a9e2789e67b8f056bc31055775a631d4c8b309373258722c393e42a2304e647"
      define_method(:install) do
        bin.install "termipost"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gabriel-ballesteros/termipost/releases/download/v1.0.2/termipost_1.0.2_linux_arm64.tar.gz"
      sha256 "13af707eb43a5a0f91bd0c4502040c69bb5ebe4042837c18e949517ef8fde723"
      define_method(:install) do
        bin.install "termipost"
      end
    end
  end

  test do
    system "#{bin}/termipost", "--version"
  end
end
