# This file was generated by GoReleaser. DO NOT EDIT.
cask "termipost" do
  version "1.4.0"

  on_macos do
    on_intel do
      sha256 "369560ef4654a05cae13ab4a10efc84b85a5579bfe80396b8426953a45585923"
      url "https://github.com/gabriel-ballesteros/termipost/releases/download/v#{version}/termipost_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "dd8b41853464123271d2e376829fdb7f73453db7ed2f5f1ff202a71a864cce0b"
      url "https://github.com/gabriel-ballesteros/termipost/releases/download/v#{version}/termipost_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "92049f70fbb9d446d747668b3a9533d4c49ed3d7d7c5c96db83a75d9fc3e9917"
      url "https://github.com/gabriel-ballesteros/termipost/releases/download/v#{version}/termipost_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "848f671f72de31a8a9ca4482bd7d2bb4d42fb563421d931df4316749b02eefd5"
      url "https://github.com/gabriel-ballesteros/termipost/releases/download/v#{version}/termipost_#{version}_linux_arm64.tar.gz"
    end
  end

  name "termipost"
  desc "A Postman-like HTTP client for the terminal."
  homepage "https://github.com/gabriel-ballesteros/termipost"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "termipost"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/termipost"]
    end
  end

  # No zap stanza required

end
