# This file was generated by GoReleaser. DO NOT EDIT.
cask "termipost" do
  version "1.3.0"

  on_macos do
    on_intel do
      sha256 "6d2f9d621d36bcffb7620f003786b374f95ac40e5f370891261524028ced739c"
      url "https://github.com/gabriel-ballesteros/termipost/releases/download/v#{version}/termipost_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a1d24945466ed4c918c57d04d52a5e33318ffb4cc36ae9b2eda99a1e7ffea7ae"
      url "https://github.com/gabriel-ballesteros/termipost/releases/download/v#{version}/termipost_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "27c1a8b1d4395b5d699f7af8f50c805b6c68c714872c94968fce9ad9f42fecd8"
      url "https://github.com/gabriel-ballesteros/termipost/releases/download/v#{version}/termipost_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "60ad9763593ff062e85c60d3ff9d0c293d214544f2dc4f13c8d43c989183dcb4"
      url "https://github.com/gabriel-ballesteros/termipost/releases/download/v#{version}/termipost_#{version}_linux_arm64.tar.gz"
    end
  end

  name "termipost"
  desc "A Postman-like HTTP client for the terminal."
  homepage "https://github.com/gabriel-ballesteros/termipost"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "termipost"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/termipost"]
    end
  end

  # No zap stanza required

end
