# This file was generated by GoReleaser. DO NOT EDIT.
cask "termipost" do
  version "1.2.1"

  on_macos do
    on_intel do
      sha256 "32319aa549770b7a6941be598528d334db6161da791c73545d2a21cbdeb3aef4"
      url "https://github.com/gabriel-ballesteros/termipost/releases/download/v#{version}/termipost_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "050b631cf15a99053c068231a1c4acdf3f92d32560a3b4920908f80ba4669bee"
      url "https://github.com/gabriel-ballesteros/termipost/releases/download/v#{version}/termipost_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ff38e6f08a742e7c906f176283bfec942059094cbd314e0c1bb5e9d87fd12dca"
      url "https://github.com/gabriel-ballesteros/termipost/releases/download/v#{version}/termipost_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "08b5ff1fea8f64587c99a79653fabe789debaffc65868dd62d4792515ec59dfe"
      url "https://github.com/gabriel-ballesteros/termipost/releases/download/v#{version}/termipost_#{version}_linux_arm64.tar.gz"
    end
  end

  name "termipost"
  desc "A Postman-like HTTP client for the terminal."
  homepage "https://github.com/gabriel-ballesteros/termipost"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "termipost"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/termipost"]
    end
  end

  # No zap stanza required

end
