# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Termipost < Formula
  desc "A Postman-like HTTP client for the terminal."
  homepage "https://github.com/gabriel-ballesteros/termipost"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gabriel-ballesteros/termipost/releases/download/v1.0.3/termipost_1.0.3_darwin_amd64.tar.gz"
      sha256 "501bc8cf2f7e74426440070d3a0c7c5f16c307a5d5badbec8eac1f1c92efc0c2"

      define_method(:install) do
        bin.install "termipost"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gabriel-ballesteros/termipost/releases/download/v1.0.3/termipost_1.0.3_darwin_arm64.tar.gz"
      sha256 "059f53e1517895df6e292d6a89e49a51df99fcacf4f0559e835b1e425bb7aa3e"

      define_method(:install) do
        bin.install "termipost"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gabriel-ballesteros/termipost/releases/download/v1.0.3/termipost_1.0.3_linux_amd64.tar.gz"
      sha256 "601f5c3b3ff1469793aff7454adde83b4ac3610ab21a00b7affa151c6b664920"
      define_method(:install) do
        bin.install "termipost"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gabriel-ballesteros/termipost/releases/download/v1.0.3/termipost_1.0.3_linux_arm64.tar.gz"
      sha256 "76eff7a9f87e23539646d5992f624c436f67332dfd4a5db93d9924f04487cd49"
      define_method(:install) do
        bin.install "termipost"
      end
    end
  end

  test do
    system "#{bin}/termipost", "--version"
  end
end
